//LOGIN
export const LOGIN='LOGIN';
export const LOGIN_FAILED='LOGIN_FAILED'
//DASHBOARD 
export const LOADING = 'LOADING';
export const FETCH_DASHBOARD='FETCH_DASHBOARD';
export const FETCH_DASHBOARD_FAILED='FETCH_DASHBOARD_FAILED'

